export const articulos = [
  {
    id: 1234561,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Cartera de cuero",
    price: "25.000",
    location: "Santiago",
    condition: "Usado",
    description: "Cartera en buen condition, color café oscuro.",
    category: "Mujer",
    vendedor: "Pedro Soto",
    email: "pedro.soto@mail.com"
  },
  {
    id: 1234562,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Zapatillas Nike",
    price: "55.000",
    location: "Valparaíso",
    condition: "Nuevo",
    description: "Zapatillas sin uso, talla 42.",
    category: "Hombre",
    vendedor: "Camila Rojas",
    email: "camila.rojas@mail.com"
  },
  {
    id: 1234563,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Chaqueta impermeable",
    price: "18.000",
    location: "Concepción",
    condition: "Usado",
    description: "Chaqueta para niño, talla 8.",
    category: "Niñ@s",
    vendedor: "Luis Fernández",
    email: "luis.fernandez@mail.com"
  },
  {
    id: 1234564,
    image_url: "https://pigmenton.cl/wp-content/uploads/2023/01/Polera-Mujer-Estampado-Amor.webp",
    title: "Polera estampada",
    price: "12.000",
    location: "La Serena",
    condition: "Nuevo",
    description: "Polera de algodón, talla M.",
    category: "Mujer",
    vendedor: "Ana Morales",
    email: "ana.morales@mail.com"
  },
  {
    id: 1234565,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Reloj de pulsera",
    price: "30.000",
    location: "Antofagasta",
    condition: "Nuevo",
    description: "Reloj dorado elegante.",
    category: "Accesorios",
    vendedor: "Juan Pérez",
    email: "juan@ejemplo.com"
  },
  {
    id: 1234566,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Jeans Levi's",
    price: "40.000",
    location: "Rancagua",
    condition: "Usado",
    description: "Jeans azul oscuro, talla 32.",
    category: "Hombre",
    vendedor: "Valentina Herrera",
    email: "valentina.herrera@mail.com"
  },
  {
    id: 1234567,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Vestido floreado",
    price: "22.000",
    location: "Temuco",
    condition: "Usado",
    description: "Vestido largo, ideal para verano.",
    category: "Mujer",
    vendedor: "Daniel Paredes",
    email: "daniel.paredes@mail.com"
  },
  {
    id: 1234568,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Mochila escolar",
    price: "15.000",
    location: "Arica",
    condition: "Usado",
    description: "Mochila resistente con varios compartimentos.",
    category: "Niñ@s",
    vendedor: "Sofía Contreras",
    email: "sofia.contreras@mail.com"
  },
  {
    id: 1234569,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Lentes de sol",
    price: "20.000",
    location: "Iquique",
    condition: "Nuevo",
    description: "Lentes UV400 polarizados.",
    category: "Accesorios",
    vendedor: "Carlos Vidal",
    email: "carlos.vidal@mail.com"
  },
  {
    id: 12345610,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Chaqueta de cuero",
    price: "90.000",
    location: "Santiago",
    condition: "Nuevo",
    description: "Chaqueta negra, corte clásico.",
    category: "Hombre",
    vendedor: "María Escobar",
    email: "maria.escobar@mail.com"
      },
  {
    id: 12345611,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Blusa manga larga",
    price: "18.000",
    location: "Viña del Mar",
    condition: "Nuevo",
    description: "Blusa de gasa, talla S.",
    category: "Mujer",
    vendedor: "Francisco Navarro",
    email: "francisco.navarro@mail.com"
  },
  {
    id: 12345612,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Gorro de lana",
    price: "10.000",
    location: "Puerto Montt",
    condition: "Usado",
    description: "Gorro tejido a mano.",
    category: "Accesorios",
    vendedor: "Isabel Fuentes",
    email: "isabel.fuentes@mail.com"
  },
  {
    id: 12345613,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Shorts deportivos",
    price: "12.000",
    location: "Talca",
    condition: "Nuevo",
    description: "Shorts para niño, talla 10.",
    category: "Niñ@s",
    vendedor: "Tomás Gallardo",
    email: "tomas.gallardo@mail.com"
  },
  {
    id: 12345614,
    image_url: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRFxoTx1D8O6VfhsTY5WJz6WD-DOOhR-36TmInUa2kH9AFzkURb8hEfQhqLl9BHh54-n6rHmXPmMbRQvi8HXCre2gznjGpYJYJefl0RL42S8aCpPVdDjikuhCQD9C5nJ-dV1Knn9-s&usqp=CAc",
    title: "Pantalón de vestir",
    price: "28.000",
    location: "Copiapó",
    condition: "Usado",
    description: "Pantalón negro, talla 38.",
    category: "Mujer",
    vendedor: "Fernanda Salas",
    email: "fernanda.salas@mail.com"
  },
  {
    id: 12345615,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Cinturón de cuero",
    price: "15.000",
    location: "Santiago",
    condition: "Nuevo",
    description: "Cinturón unisex, ajustable.",
    category: "Accesorios",
    vendedor: "Ignacio Méndez",
    email: "ignacio.mendez@mail.com"
      },
  {
    id: 12345616,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Zapatos de vestir",
    price: "55.000",
    location: "Valdivia",
    condition: "Usado",
    description: "Zapatos negros, poco uso.",
    category: "Hombre",
    vendedor: "Matías Orellana",
    email: "matias.orellana@mail.com"
  },
  {
    id: 12345617,
    image_url: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTRwgbbygWfPWUNbIpOGdDwTdfBzeZQf_36LOYzOr-xYaFT6pjEXsRuIov-7ctb4Mj23nufB-RgReOWdXRcCgDGcvtTmRd52dJqe70OJJn8-mwokL12ncpr&usqp=CAc",
    title: "Vestido de fiesta",
    price: "25.000",
    location: "Chillán",
    condition: "Nuevo",
    description: "Vestido rosa para niña, talla 6.",
    category: "Niñ@s",
    vendedor: "Daniela Reyes",
    email: "daniela.reyes@mail.com"
  },
  {
    id: 12345618,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Bufanda tejida",
    price: "8.000",
    location: "Punta Arenas",
    condition: "Usado",
    description: "Bufanda de lana color burdeo.",
    category: "Accesorios",
    vendedor: "Antonia Zamora",
    email: "antonia.zamora@mail.com"
  },
  {
    id: 12345619,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Falda de mezclilla",
    price: "20.000",
    location: "Ovalle",
    condition: "Nuevo",
    description: "Falda con bolsillos, talla M.",
    category: "Mujer",
    vendedor: "Benjamín Cáceres",
    email: "benjamin.caceres@mail.com"
  },
  {
    id: 12345620,
    image_url: "https://marketing4ecommerce.cl/wp-content/uploads/2021/09/nueva-portada-enero-11.jpeg",
    title: "Chaqueta de jean",
    price: "19.000",
    location: "Calama",
    condition: "Usado",
    description: "Chaqueta para niñ@, talla 12.",
    category: "Niñ@s",
    vendedor: "Juan Pérez",
    email: "juan@ejemplo.com"
  }
];

